var name ="Vaibhav Sanjay Sase";
var school ="Shree Santuknath English Vidyalaya ";
var grade ="A";
var section ="A";
var rollno = 21;
var English = 93;
var Marathi =94;
var Mathematics =96;
console.log("     ~~~~~~~~~~~~~~~~~~~~     ");
console.log("       ================       ");
console.log("----------REPORT CARD----------");
console.log("       ================        ");
console.log("     ~~~~~~~~~~~~~~~~~~~~     ");
console.log("");
console.log("");
console.log("");
console.log("Name         -   " +name);
console.log("");
console.log("School       -   "+ school);
console.log("");
console.log("Grade        -   "+ grade);
console.log("Section      -   "+ section);
console.log("Roll No      -   "+ rollno);
console.log( "English      -   "+ English);
console.log("Marathi      -   " +Marathi);
console.log("Mathematics  -   " +Mathematics);
console.log("");
console.log("");
console.log("---------Thank You------------");
console.log("");
console.log("");

